name: flutter_web_qrcode_scanner
description: Camera-based QR code scanning for Flutter-Web,  The package makes use of the jsQR.js library to gain native access to the camera and scan QR codes
version: 1.1.1
homepage: https://github.com/moho4141/flutter_web_qrcode_scanner

environment:
  sdk: '>=2.15.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cross_file: ^0.3.3+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterWebQrcodeScannerWeb
        fileName: flutter_web_qrcode_scanner_web.dart